name: Build Docker

on:
  push:
  pull_request:
    branches: [main]

env:
  BEEPER_BRIDGE_TYPE: ai
  CI_REGISTRY_IMAGE: "${{ secrets.CI_REGISTRY }}/bridge/ai"
  GHCR_REGISTRY: ghcr.io
  GHCR_REGISTRY_IMAGE: "ghcr.io/${{ github.repository }}"

jobs:
  build-docker:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@8d2750c68a42422c14e847fe6c8ac0403b4cbd6f # v3.12.0

    - name: Login to Beeper Docker registry
      uses: docker/login-action@5e57cd118135c172c3672efd75eb46360885c0ef # v3.6.0
      with:
        registry: ${{ secrets.CI_REGISTRY }}
        username: ${{ secrets.CI_REGISTRY_USER }}
        password: ${{ secrets.CI_REGISTRY_PASSWORD }}

    - name: Login to ghcr
      uses: docker/login-action@5e57cd118135c172c3672efd75eb46360885c0ef # v3.6.0
      with:
        registry: ${{ env.GHCR_REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Docker Build
      uses: docker/build-push-action@10e90e3645eae34f1e60eeb005ba3a3d33f178e8 # v6.19.2
      with:
        context: .
        pull: true
        file: ./Dockerfile
        tags: |
          ${{ env.CI_REGISTRY_IMAGE }}:${{ github.sha }}
          ${{ env.GHCR_REGISTRY_IMAGE }}:${{ github.sha }}
        push: true

  deploy-docker:
    runs-on: ubuntu-latest
    needs:
    - build-docker
    if: github.ref == 'refs/heads/main'
    steps:
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@8d2750c68a42422c14e847fe6c8ac0403b4cbd6f # v3.12.0

    - name: Login to Beeper Docker registry
      uses: docker/login-action@5e57cd118135c172c3672efd75eb46360885c0ef # v3.6.0
      with:
        registry: ${{ secrets.CI_REGISTRY }}
        username: ${{ secrets.CI_REGISTRY_USER }}
        password: ${{ secrets.CI_REGISTRY_PASSWORD }}

    - name: Login to ghcr
      uses: docker/login-action@5e57cd118135c172c3672efd75eb46360885c0ef # v3.6.0
      with:
        registry: ${{ env.GHCR_REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - uses: beeper/docker-retag-push-latest@72a38e93b5fe9b5a4f300988adab0a9558365e81 # main
      with:
        image: ${{ env.CI_REGISTRY_IMAGE }}

    - uses: beeper/docker-retag-push-latest@72a38e93b5fe9b5a4f300988adab0a9558365e81 # main
      with:
        image: ${{ env.GHCR_REGISTRY_IMAGE }}

    - name: Run bridge CD tool
      uses: beeper/bridge-cd-tool@208d6029cf9d3d1d343036fc2d8cac5d11f42eed # main
      env:
        CI_REGISTRY: "${{ secrets.CI_REGISTRY }}"
        BEEPER_DEV_ADMIN_API_URL: "${{ secrets.BEEPER_DEV_ADMIN_API_URL }}"
        BEEPER_STAGING_ADMIN_API_URL: "${{ secrets.BEEPER_STAGING_ADMIN_API_URL }}"
        BEEPER_PROD_ADMIN_API_URL: "${{ secrets.BEEPER_PROD_ADMIN_API_URL }}"
        BEEPER_DEV_ADMIN_NIGHTLY_PASS: "${{ secrets.BEEPER_DEV_ADMIN_NIGHTLY_PASS }}"
        BEEPER_STAGING_ADMIN_NIGHTLY_PASS: "${{ secrets.BEEPER_STAGING_ADMIN_NIGHTLY_PASS }}"
        BEEPER_PROD_ADMIN_NIGHTLY_PASS: "${{ secrets.BEEPER_PROD_ADMIN_NIGHTLY_PASS }}"
